### ISSUE TITLE
Integrate woodstock 4.1.0 in Eclipse GlassFish

### ISSUE THREAD

**Issue by romain-grecourt** [eclipse-ee4j/glassfish-woodstock#1399]
The latest updates to woodstock (v5.x) need to be integrated back in GlassFish.

The GF admingui of 5.1.0 has some issues, most likely introduced with the upgrade of DOJO and the use of the asynchronous mode.

Double check that we are not loosing any more functionality with this new version.
The main goal of 5.x is to make the project easier to maintain so that bugs can be fixed easily.

Here are some of the issues I noticed on the GF admin console:
- most dropDown menu don't trigger actions
- Click "Configurations" / "server-config" / "Admin Service", then click on the "SSL" tab and then click "save", this results in a page with no styles
- Deploy an application and click "Applications" / "your app", the click on the "Descriptor" tab and click on the link of one of the deployment descriptor (note the spinning wheel is not going away), then click back. This results in a bare page that is displayed before a redirect.

These issues are likely not introduced by the changes made to 5.x.

There are Javascript issues, see #1398. Fixing them will require updating the javascript code in the GF admin console.

We also need to make sure to test the fileupload functionally (UploadFilter).

Also note that the GF admin console has an automated test suite.

**Comment by pzygielo** [comment]
With current glassfish 7.0.x using 6.0.1 I consider this done.
