### ISSUE TITLE
Create 4.1.0 branch for maintenance

### ISSUE THREAD

**Issue by hs536** [eclipse-ee4j/glassfish-woodstock#1409]
I created 4.1.0 branch (as a non-jakarta-ized branch) for maintenance from eclipse-ee4j/glassfish-woodstock@60372f2 .
see also : https://github.com/eclipse-ee4j/glassfish/issues/23038

**Comment by gerdogdu** [comment]
Hi
I looked to the code common.js but this is not same common.js in 4.0.2.16? Is this change from 4.0.x to 4.1.x?

**Comment by gerdogdu** [comment]
Attached is the common.js from 4.0.2.16
[common.js.zip](https://github.com/eclipse-ee4j/glassfish-woodstock/files/4728822/common.js.zip)

**Comment by hs536** [comment]
There probably are some changes. Please check the history of common.js.

**Comment by hs536** [comment]
This issue was created to clarify the role of the 4.1.0 branch. I already created a branch, so close this.
